### ISSUE TITLE
train, translate cfg used in paper

### ISSUE THREAD

**Issue by Sanghyuk-Choi** [KaijuML/data-to-text-hierarchical#10]
Hi,
I've just cloned this repo and following the instructions in README.
I think the configurations(train.cfg, translate.cfg) in this repo are slightly different from the paper such as hidden size, beam size, etc...
Can I get the configurations of train and translate that used in original paper?
Thank you.

**Comment by KaijuML** [comment]
Hi, thank you for your concern. I will push in the next minutes the correct `train.cfg` file. 

I am closing this issue for now, however do not hesitate to let me know if you need anything else!
