### ISSUE TITLE
Issue while Training 

### ISSUE THREAD

**Issue by Vrishiket** [KaijuML/data-to-text-hierarchical#13]
Hi I tried Running the training code, but I'm getting ascii error, can you provide a checkpoint file for the same 

Thanks 

Vrishiket

**Comment by KaijuML** [comment]
Hello,

I have included model outputs and checkpoints. Note that the checkpoints are not the exact one used to produce the model outputs, but were graciously provided by others working on the project. Model outputs are the original though!

See README for instructions.
