### ISSUE TITLE
Unnecessary code is contained in make-dataset.py .

### ISSUE THREAD

**Issue by JaeShinJun** [KaijuML/data-to-text-hierarchical#2]
` player_city = nplayers = entry['box_score']['TEAM_CITY'][str(i)]`
I think "nplayers =" part was mistakenly written!

       
https://github.com/KaijuML/data-to-text-hierarchical/blob/26465720f0953685c0fd079636a6e33afc9561e5/data/make-dataset.py#L84

**Comment by KaijuML** [comment]
Thanks, I fixed it!
