### ISSUE TITLE
some wrong when traning 

### ISSUE THREAD

**Issue by laity-slf** [KaijuML/data-to-text-hierarchical#32]
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/59203496/176992139-089cfeae-90e1-40a2-880c-c5aff721b979.png">

I use the recommended env, but it still makes a mistake.

**Comment by laity-slf** [comment]
since my GPU is RTX3090, I guess the Cuda version is not matched

**Comment by KaijuML** [comment]
Hey, I would also guess this is a CUDA version issue. Are you able to try with an older version?

**Comment by laity-slf** [comment]
> 

OK, I have solved it now. Thank you for your reply.
