### ISSUE TITLE
Issues running automatic evaluations

### ISSUE THREAD

**Issue by sirmammingtonham** [KaijuML/data-to-text-hierarchical#8]
Hi,
Thanks for the awesome paper and the code! 

I was having trouble getting the evaluation metric `extractor.lua` script to work properly, mainly getting 'bad argument #1 to 'copy' when running the models linked on the harvardnlp repo. I also tried with [ratishsp's fork](https://github.com/ratishsp/data2text-1) which has an updated model with a fix for number words, which runs fine but I'm not getting comparable results using that. 

I saw you mentioned in the README that you also had some problems running the automatic evals so I was wondering how you managed to overcome them.

Thanks for the help,
Ethan

**Comment by KaijuML** [comment]
Hello Ethan,

Appologies for the late answer. 

I have just made public a repository where the RG-metric is coded in modern Pytorch:

https://github.com/KaijuML/rotowire-rg-metric

Please let me know if you have any issue, I promise to be more reactive than I was last year!

I am closing this issue, feel free to reopen if needed.
